### PR TITLE
comp plot functions

### PR DESCRIPTION
**Pull request by ajtsao1**
@aarmey I wasn’t able to push on the other branch I’d been working on so I added the functions for receptor-specific pY and dimers to this new branch. Right now, the functions take in either one receptor-specific vector or one dimer vector, and can plot multiple timepoints. If this would be better, I can also change the dimer function to take in multiple vectors for each dimer type and plot them all at one timepoint.
Also, now that I have the notebook running again, I will finish up the normalization plots. I'll probably add that here and delete the other branch since I kept getting a bunch of merge conflicts.

### CODE REVIEW

**Comment by ajtsao1** [comment]
@aarmey I added the normalized pY plot to the notebook here. Just to make sure, the total and totalC vectors in reactCode are for total receptor, correct? I used totalC for the normalization and the spatial pattern doesn’t seem to have changed much.

**Review by aarmey — APPROVED** [review]
Yes, this looks correct. The profile looks quite different to me! This is helpful as it looks like the change in pY is mostly via increased receptor density.

**Comment by ajtsao1** [comment]
@aarmey Oh okay, I wasn't sure how to interpret the results but I see that now. Cool! I can add this plot as a function if that will be helpful. Is there anything else I should take a look at next?

**Comment by aarmey** [comment]
I know you've looked at whether the diffusion rate or Gas6 partitioning affects the spatial profile (and they didn't). It would be good to know, now, whether they affect the magnitude of pY in the center. For example, perhaps you could make a plot of pY in the center over time, then play with these parameters?

I'll also check in with Sumedha about the MTK changes. With that and this we may have enough to start writing up results.

**Review by aarmey — APPROVED** [review]
I think we can just merge what you have here for now.

**Comment by ajtsao1** [comment]
@aarmey Okay, I will try those out! And it looks like merging is blocked for me but maybe you are able to.

**Pull request merged**
