### PR TITLE
Param plots and Chains tests

### PR DESCRIPTION
**Pull request by sumedha-k**
@aarmey There's two commits in this PR:

the first is just the params plots that we wanted to look (kRec vs. kDeg, gasCur vs. AXLexpr, and internalize vs. xFwd). I included the new chain file in this commit

the second adds a test which checks if we are able to read the parameters from the chains file

### CODE REVIEW

**Comment by aarmey** [comment]
Looks like it's failing because DataFrames isn't added as a package dependency. Can you add that?

**Comment by aarmey** [comment]
It looks like it's failing now because Gadfly is missing. If you click on "details" you can see all the output from the testing run to see why it failed.

Have you run the tests yourself by calling `Pkg.test()`? That might give you quicker feedback as to whether it will work.

**Comment by sumedha-k** [comment]
Sorry I don't think I resolved the merge conflicts properly, I'll fix it later today

**Review by aarmey — APPROVED** [review]
Less correlation between those parameters than I would have expected, but this all looks great. Ready to merge when it finishes building.

**Pull request merged**
