### PR TITLE
model notebook

### PR DESCRIPTION
**Pull request by sumedha-k**
Type error with params

### CODE REVIEW

**Comment by sumedha-k** [comment]
@aarmey I am getting an error when I run sample. I think runTAM or one of the functions it calls is expecting a Float64 but we're giving it a distribution. I wasn't sure how to approach this issue.

**Comment by sumedha-k** [comment]
@aarmey ignore the code in compModel, I didn't mean to add that to the PR

**Comment by aarmey** [comment]
@sumedha-k is there supposed to be a notebook here?

**Comment by sumedha-k** [comment]
@aarmey yes the notebook is called runTAM.pynb, I committed a total of three files. If it is not showing up, you can find it at the bottom of the compMod branch code.

**Comment by sumedha-k** [comment]
@aarmey I also just committed TAM_react, however some of the functions that it was calling have pointer variables go I was not sure what to do with those

**Comment by aarmey** [comment]
Don't worry about compmodel. I need to do some rethinking of how that is organized.

**Comment by aarmey** [comment]
I think what I just pushed is basically working, with one caveat I haven't worked around. We can discuss tomorrow, along with what I changed and why.

**Pull request merged**
