### PR TITLE
fixes to plots

### PR DESCRIPTION
**Pull request by sumedha-k**

### CODE REVIEW

**Comment by aarmey** [comment]
@sumedha-k I just merged #218 to master. I think this is the source of the issue—try fitting again with this change.

**Comment by sumedha-k** [comment]
@aarmey I got this error while I was trying to fit. 
┌ Warning: The current proposal will be rejected due to numerical error(s).
│   isfinite.((θ, r, ℓπ, ℓκ)) = (true, false, false, false)
└ @ AdvancedHMC ~/.julia/packages/AdvancedHMC/WJCQA/src/hamiltonian.jl:47

**Comment by aarmey** [comment]
@sumedha-k try lowering the solver tolerance. Change `solTol` to 1e-9.

https://github.com/meyer-lab/TAMode.jl/blob/master/src/TAMode.jl#L17

**Comment by sumedha-k** [comment]
@aarmey I'm still getting the same warning

**Comment by aarmey** [comment]
Does the fitting stop? Because this warning can happen while fitting successfully continues.

**Comment by sumedha-k** [comment]
It errors and exits

**Comment by aarmey** [comment]
Still looking into this.

**Comment by aarmey** [comment]
@sumedha-k just pushed some changes that seem to fix this. I got some warnings during fitting, but it ran to completion. Try fitting again.

**Comment by sumedha-k** [comment]
@aarmey I was able to run the fitting, and I just pushed the new plots. The results still don't match the experimental data.

**Comment by aarmey** [comment]
Huh... what's especially surprising to me is that the plots look essentially the same. If you happen to have the older sampling around, can you confirm whether the fitting results you got have changed much, and how different the plots look as compared to before? If nothing has changed then maybe I'm misunderstanding how to setup a Turing model...

**Comment by sumedha-k** [comment]
@aarmey the plots notebook now has plots for both the old and new fitting. There does appear to be a difference in at least the pY receptor plots.

**Comment by aarmey** [comment]
These are remarkably similar...

Can you take one sample from the chain, and do the following comparison between the model and data? You should end up with the same number as the `sqResid` value stored in the chain. I'm almost certain we must have an error somewhere, but if this matches up then the plotting code is definitely correct.

```
sqResid = sqeuclidean(pYmodel, pYdata)
sqResid += sqeuclidean(totalmodel, totalData) / 100.0
sqResid += sqeuclidean(surfmodel, surfData) / 0.038
```

**Comment by sumedha-k** [comment]
@aarmey  When I tried to run the fitting, I got the following error:
Test sampling.: Error During Test at /home/sumedhak/TAMode.jl/src/sampling.jl:5
  Got exception outside of a @test
  AssertionError: params[3] < 1.0
  Stacktrace:
   [1] param(::Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:internalize, :pYinternalize, :sortF, :kRec, :kDeg, :xFwd, :gasCur, :AXLexpr, :Ig2rev, :scale, 

Not sure what we changed that do would have caused this to happen

**Comment by aarmey** [comment]
@sumedha-k  Fixed in last commit. `sortF` was ending up equal to 1 which didn't work with the assertion. That value is fine so I made the assertion `<=`. I tried out the sampling and got to ~10% without issues.

**Pull request closed without merging**
